import type { Metadata } from "next";
import "./globals.css";

import { ebgaramond, lexend, merriweather, roboto } from "@/font/font";
import AnnouncementComponent from "@/components/announcement";
import HeaderComponent from "@/components/header";

export const metadata: Metadata = {
  title: "Polish Club of Hunter College",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${ebgaramond.variable} ${lexend.variable} ${merriweather.variable} ${roboto.variable} bg-slate-50`}>
        {/* <AnnouncementComponent /> */}
        <HeaderComponent />
        {children}
      </body>
    </html>
  );
}
